name: technician
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rflutter_alert: ^2.0.2
  transparent_image: ^2.0.0
  timeline_tile: ^2.0.0
  timeline_list: ^0.0.3
  image_picker: ^0.8.1+1
  dio: ^4.0.0
  flutter_image_slideshow: ^0.1.0  
  shared_preferences: ^2.0.6 
  firebase_messaging: ^14.2.1
  firebase_core: ^2.4.1
  intl: ^0.18.0
  direct_select: ^2.0.0
  icon_picker: ^2.1.0
  flutter_datetime_picker: ^1.5.1
  qrscan: ^0.3.2
  flutter_animated_dialog: ^2.0.1
  searchable_dropdown: ^1.1.3
  responsive_flutter: ^0.0.4
  package_info: ^2.0.2
  # geocoding: ^2.0.1
  decorated_icon: ^1.2.1
  permission_handler: ^10.2.0
  geolocator: ^9.0.2
  geocoding: ^2.0.1
  # qrscans: ^0.0.7
  # searchable_dropdown: ^1.1.3




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  # geolocator: ^7.2.0+1
  google_maps_flutter: ^2.0.6
  # flutter_background_geolocation: ^4.2.1  
  

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

  http:
  flutter_local_notifications:
  url_launcher: ^6.0.9  
  
  flutter_test:
    sdk: flutter  
  
  # permission_handler: any

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/logo_twyshop.png
    - images/contact.jpg
    - images/phone.png
    - images/contactfilter.jpg
    - images/icons-h.gif
    - images/logo_twy.png
    - images/icon-warning.png
    - images/icon-warning2.png
    - images/logo_twy_w.png
    - images/delivery-truck.png
    - images/truck.png
    - images/shop.png
    - images/logo_home.png
    - images/dashbord.jpg
    - images/dashbord2.jpg
    - images/dashbord3.jpg
    - images/dashbord4.jpg
    - images/line_b.png
    - images/success.png
    - images/logo_mc.png  
    - images/history.png
    - images/camera.png
    - images/quest.png
    - images/logo_mc2.png 
    - images/user.png
    - images/trash_can.png
    - images/log_load.gif
    - images/log_time.gif
    - images/bin.gif
    - images/error_log.gif
    - images/error_pin.gif
    - images/icon_c.png
    - images/logo_mc3.png
    - images/add_checker.gif
    - images/no_success.gif
    - images/success.gif
    - images/logo.png
    - images/load_img.gif
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Prompt
      fonts:
        - asset: fonts/Prompt-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
